nome = input('Olá, nós somos seu leitor de texto e caracteres.\nQual seu nome? ')
print(f'Prazer em conhecer, {nome}. nós vamos ler e interpretar todas as caracteres desejada do seu texto ou frase.\nMas antes precisamos de algumas informações básicas primerio.')
idade = input('Qual sua idade? ')
input('Informe seu email para salvarmos suas ações no nosso sistema: ')
print('Prontinho agora é só confirmar nossa mensagem no email que enviamos a voçê...')
input(f'{nome}, agora é só teclar enter para podermos te ajudar com seu texto. ')
texto = input(f'{nome}, Cole ou escreva um texto ou uma frase para podermos ler ou talvez até ediar ela se você preferir: ')
print('\n\nSeu Texto tem exatamente...')
print('\nnúmeros de caracetres (contando os espaços:')
print(len(texto))
print('Números de letras MINUSCÚLAS:')
print(texto.lower())